### PR TITLE
made version of minikube configurable

### PR DESCRIPTION
**Pull request by sebastian-toepfer**

### CODE REVIEW

**Comment by medyagh** [comment]
@sebastian-toepfer thank you for this PR do u mind adding pull upstream ?
and sorry for the late review

**Comment by sebastian-toepfer** [comment]
@medyagh: done, if this pr is done, i will pull upstream for the macos one

**Comment by sebastian-toepfer** [comment]
@medyagh sry, but whats about this pr? would be very nice to get this and the macos one merged and a quick release - so we must no longer used the fork.

**Review by medyagh — APPROVED** [review]
thank you very much and sorry for such a long long time on waiting for review

**Pull request merged**
