### PR TITLE
Add Insecure registry configuration (#49)

### PR DESCRIPTION
**Pull request by radtriste**
https://github.com/medyagh/setup-minikube/issues/49

### CODE REVIEW

**Comment by radtriste** [comment]
@medyagh testing in progress

**Comment by radtriste** [comment]
tested in https://github.com/kiegroup/kogito-serverless-operator/actions/runs/3702516960/jobs/6273476716 successfully

**Comment by radtriste** [comment]
cc @spowelljr

**Comment by medyagh** [comment]
@radtriste do you mind rebuilding the npm we just did some changes and please rebase your PR

**Review by spowelljr — APPROVED** [review]
Thanks for the PR!

**Comment by radtriste** [comment]
@spowelljr @medyagh Thank you for the merge !
Would it be possible to release this new version so we can use it in our GHA ?

**Comment by medyagh** [comment]
@radtriste sounds good I will do a release right now

**Comment by spowelljr** [comment]
@radtriste Just as a FYI if you always change your setup-minikube to use master to access changes on master that are not yet released.

`medyagh/setup-minikube@latest` -> `medyagh/setup-minikube@master`

**Comment by radtriste** [comment]
@medyagh Thank you for the release, gonna use it !
@spowelljr I prefer to use a specific version, aka now `v0.0.10` to avoid any future non backward change problems

**Pull request merged**
