### PR TITLE
Support minikube --addons & --extra-config (dup)

### PR DESCRIPTION
**Pull request by bushwhackr**
+ Enable addons flag when setting up minikube
+ Upgraded actions/checkout

### CODE REVIEW

**Comment by bushwhackr** [comment]
Added extra options commit from #33

**Review by flopotok — APPROVED** [review]
LGTM

**Comment by bushwhackr** [comment]
is there anything blocking the merging of this PR?

**Comment by medyagh** [comment]
[bushwhackr](https://github.com/bushwhackr) thanks for this PR and sorry for the delay in the review

**Pull request merged**
